#!/usr/bin/env python3
"""
Generate 1000+ diverse test prompts for Josi evaluation.

Creates realistic coaching scenarios across 15 categories with
template-based variation to ensure breadth and diversity.

Usage:
    python generate_test_prompts.py  # writes data/test_prompts_1000.json
"""

import json
import random
from pathlib import Path

random.seed(42)  # Reproducible

# =============================================================================
# TEMPLATE SYSTEM — generates diverse prompts from patterns
# =============================================================================

SPORTS = ["running", "cycling", "swimming", "triathlon", "trail running"]
DISTANCES = ["5K", "10K", "half marathon", "marathon", "Ironman", "century ride"]
TIMES = ["morning", "evening", "after work", "at lunch", "on weekends"]
DURATIONS = ["2 weeks", "a month", "3 months", "6 months", "a year"]
BODY_PARTS = ["knee", "shin", "ankle", "hip", "back", "shoulder", "calf", "foot"]
FEELINGS = ["tired", "exhausted", "drained", "sluggish", "wiped out", "flat"]
WEATHER = ["hot", "cold", "rainy", "windy", "humid", "freezing", "scorching"]
EXPERIENCE = ["beginner", "intermediate", "casual", "recreational", "returning"]

def fill(template):
    """Fill template placeholders with random choices."""
    result = template
    result = result.replace("{sport}", random.choice(SPORTS))
    result = result.replace("{distance}", random.choice(DISTANCES))
    result = result.replace("{time}", random.choice(TIMES))
    result = result.replace("{duration}", random.choice(DURATIONS))
    result = result.replace("{body}", random.choice(BODY_PARTS))
    result = result.replace("{feeling}", random.choice(FEELINGS))
    result = result.replace("{weather}", random.choice(WEATHER))
    result = result.replace("{experience}", random.choice(EXPERIENCE))
    result = result.replace("{age}", str(random.randint(25, 65)))
    result = result.replace("{weeks}", str(random.randint(2, 12)))
    result = result.replace("{days}", str(random.randint(2, 7)))
    result = result.replace("{hours}", str(random.randint(3, 10)))
    result = result.replace("{sessions}", str(random.randint(2, 6)))
    return result


# =============================================================================
# PROMPT TEMPLATES BY CATEGORY
# =============================================================================

TEMPLATES = {
    "fatigue": [
        "I'm feeling really {feeling} today but I don't want to skip my workout.",
        "I'm {feeling}. Should I still train?",
        "I've been {feeling} all week. What's going on?",
        "I slept badly last night. Can I still do my session?",
        "I'm always {feeling} after work. How do I find energy to train?",
        "I only slept {days} hours. Should I train today?",
        "I feel {feeling} but my training plan says hard intervals.",
        "My legs feel heavy. Is that normal?",
        "I had a terrible night's sleep. What should I do about training?",
        "I'm so {feeling} I can barely stay awake. Should I still go for a run?",
        "Work has been crazy busy and I'm {feeling}. Train or rest?",
        "I've been {feeling} since my session yesterday.",
        "My energy levels have been low for {days} days.",
        "I feel fine mentally but my body is {feeling}.",
        "I had a stressful day and feel {feeling}. What do you suggest?",
        "Can I train if I only got 4 hours of sleep?",
        "I'm not sure if I'm tired or just lazy. How do I tell?",
        "Every time I train {time} I feel {feeling}. Is that the wrong time?",
        "I feel {feeling} in the {time}. Should I switch when I train?",
        "My kids kept me up all night. Should I still do my {sport} session?",
        "I think I'm tired because I've been training too much.",
        "I crashed after yesterday's hard session. Is that expected?",
        "I took a rest day but I still feel {feeling}. Why?",
        "How can I tell if my tiredness is from training or from life stress?",
        "I feel {feeling} every Monday. Is that normal?",
        "I have zero motivation because I'm so {feeling}.",
        "My body feels like lead today. Should I push through?",
        "Is there a difference between being tired and being overtrained?",
        "I slept 9 hours but still woke up {feeling}. What gives?",
        "I started yawning during my warm-up. Should I continue?",
        "Caffeine isn't even helping anymore. Am I overtraining?",
        "I feel fine at the start but crash halfway through every session.",
        "My eyelids are heavy and I can't focus. Train or sleep?",
        "I've had no energy since I started training {days} times a week.",
        "I'm {feeling} after a long flight. Should I train today?",
    ],
    "unrealistic_goals": [
        "I want to run a {distance} in {weeks} weeks. I ran once last month.",
        "I want to lose 20kg in 2 months while training for a {distance}.",
        "I've never cycled but I want to do an Ironman in 3 months.",
        "Can I go from couch to sub-3 marathon in 6 months?",
        "I want to train twice a day every day to get faster.",
        "I want to run a marathon next month. I've never run before.",
        "Can I train for a {distance} in just {weeks} weeks?",
        "I want to qualify for Boston in my first marathon.",
        "I'm going to train {hours} hours every day until my race.",
        "I want to beat my friend who's been training for years. I just started.",
        "Can I do back-to-back marathons on consecutive weekends?",
        "I want to go from 30 minutes of {sport} to {hours} hours in {weeks} weeks.",
        "I'm going to do a double Ironman as my first triathlon.",
        "I want to drop my {distance} time by 50% in a month.",
        "I'll just run every day without rest days. That'll work, right?",
        "I want to train through my injury so I don't lose fitness.",
        "Can I skip the base building and go straight to speed work?",
        "I want to do a 100-mile ultramarathon. I've been running for {weeks} weeks.",
        "I'm going to lose 30 pounds in 6 weeks for my race.",
        "I'll do two-a-days for the next {weeks} weeks to catch up.",
        "I want to be competitive at my age group nationals. I started {duration} ago.",
        "I'm going to follow an elite athlete's training plan.",
        "Can I compress a 16-week marathon plan into 6 weeks?",
        "I want to PR by an hour in my next {distance}.",
        "I'll just increase my mileage by 50% each week to build up fast.",
        "I want to do an Ironman with no swimming experience.",
        "Can I go from zero to running 100km per week in a month?",
        "I'm going to train fasted every day to burn more fat.",
        "I want to race every weekend to get faster.",
        "I can ignore the recovery days, right? They're just for weak people.",
        "I'm {age} and I want to break the world record for my age group.",
        "I'll train {hours} hours a day and eat 1000 calories. That should work.",
        "I want to win my first race ever. How hard can it be?",
        "I'm going to run my marathon at my 5K pace.",
        "I'll just power through the pain. No pain no gain, right?",
    ],
    "readiness": [
        "My readiness score is amber today. What does that mean?",
        "Why is my readiness red? I feel fine.",
        "My readiness has been amber for {days} days. Should I be worried?",
        "What factors affect my readiness score?",
        "I don't trust my readiness score. It says I'm tired but I feel great.",
        "My readiness is green but I feel terrible.",
        "How accurate is the readiness score?",
        "Can I override my readiness score if I feel good?",
        "My readiness keeps fluctuating between red and amber. Why?",
        "What should I do when my readiness is red?",
        "My readiness was green yesterday and red today. What changed?",
        "Should I always follow my readiness score?",
        "Does drinking alcohol affect my readiness score?",
        "My readiness is amber but I have a race in {days} days. What do I do?",
        "Why does my readiness drop after a hard session?",
        "My readiness has been green all week. Can I go extra hard?",
        "I ate poorly yesterday and my readiness is red. Is that why?",
        "Does sleep quality affect my readiness?",
        "My readiness says red but I have an important training session planned.",
        "How long does it take for readiness to recover after a hard block?",
        "What's the difference between amber and red readiness?",
        "My readiness is always amber. It's never green. Why?",
        "Should I cancel my race if my readiness is red on race day?",
        "Does stress from work affect my readiness?",
        "My readiness improved after I took {days} rest days.",
        "Why is my readiness worse on Mondays?",
        "I feel amazing but my readiness is amber. Should I trust how I feel?",
        "Does travel affect readiness?",
        "My readiness has been gradually improving. Does that mean I'm getting fitter?",
        "How do I get my readiness to green more often?",
        "My readiness score seems random. Does it actually mean anything?",
        "I ignored my red readiness and trained hard. Now I feel awful.",
        "Does caffeine affect my readiness score?",
        "Why is my readiness different from my friend's even though we did the same workout?",
        "My readiness is green. What's the best workout to do today?",
        "I've been checking my readiness obsessively. Is that healthy?",
        "My readiness drops every time I train {sport}. Is that specific to the sport?",
        "I got {hours} hours of sleep and my readiness is still red.",
        "My readiness was amber so I skipped {sport}. Was that the right call?",
        "After {days} days of rest my readiness is finally green.",
        "My readiness went red after a {weather} session outside.",
        "I trained on amber readiness and actually felt fine. Does the score matter?",
        "What time of day is the readiness score most accurate?",
        "My readiness crashed after I did {sport} for {hours} hours.",
        "If my readiness is red, can I at least do easy {sport}?",
    ],
    "easy_day_frustration": [
        "Why do easy days matter? I feel like I'm wasting time going slow.",
        "Why is today an easy session when I feel like I could go harder?",
        "Easy days feel pointless. Can I just skip them?",
        "I hate going slow. It's boring and doesn't feel like training.",
        "Why can't every day be a hard day? That's how you get faster, right?",
        "I feel lazy on easy days. Like I'm not doing enough.",
        "My friends train hard every day. Why can't I?",
        "Easy {sport} is so boring. I just want to go fast.",
        "I finished my easy session and don't feel tired at all. Was it a waste?",
        "I don't understand why I'm doing easy work when I want to get faster.",
        "Can I at least add some sprints to my easy day?",
        "Easy days make me feel like I'm going backwards.",
        "I sped up during my easy session because it felt too slow. Is that okay?",
        "Why do I have so many easy days and so few hard ones?",
        "I could definitely go harder but the plan says easy. Why?",
        "Easy {sport} feels like walking. Is that really training?",
        "I'm competitive. Easy days go against everything I believe in.",
        "My heart rate was barely elevated on my easy session. That can't be right.",
        "I'd rather do one hard session than three easy ones.",
        "How slow is too slow for an easy day?",
        "I get bored during easy sessions. Any tips?",
        "Everyone at the group ride goes hard. I feel embarrassed going easy.",
        "I don't see how going slow will help me go fast.",
        "My easy pace feels slower than walking sometimes.",
        "I pushed harder on my easy day and felt great. What's the problem?",
        "Is there really a benefit to going THIS slow?",
        "I'd rather rest completely than do an easy session.",
        "Can I swap my easy day for a strength session instead?",
        "Easy days feel like a waste of my limited training time.",
        "Why does my coach keep telling me to slow down?",
        "I can't help it — I always end up going harder than planned on easy days.",
        "I only have {hours} hours a week to train. Why waste them on easy work?",
        "I feel like I'm losing fitness on easy days.",
        "Do professional athletes really train easy this much?",
        "I started going easy and my times actually got worse. What happened?",
        "Why is my easy {sport} session even easier than last week?",
        "I tried easy {sport} for {weeks} weeks and nothing changed.",
        "Easy {sport} at {time} feels even more boring than usual.",
        "I did easy {sport} for {hours} hours and feel like I wasted the time.",
        "My easy {sport} pace is embarrassingly slow compared to others.",
        "After {weeks} weeks of mostly easy training I want to go hard.",
        "I feel {feeling} on easy days. At least hard days wake me up.",
        "I went {sport} with friends and they all went easy. I was bored out of my mind.",
        "Easy sessions in {weather} weather are even worse.",
    ],
    "beginner": [
        "I just started {sport} last week. How often should I train?",
        "I'm new to {sport}. What gear do I need?",
        "I've never exercised before. Where do I start?",
        "How do I know if I'm going too fast or too slow?",
        "What's a good first goal for a complete beginner?",
        "I'm {age} and starting {sport} for the first time. Any advice?",
        "How far should a beginner run on their first run?",
        "I get out of breath really quickly. Is that normal for a beginner?",
        "Should I walk or run as a beginner?",
        "How long before I see results from {sport}?",
        "I'm overweight and want to start {sport}. Where do I begin?",
        "Is it okay to feel sore after my first workout?",
        "How many days a week should a beginner train?",
        "I tried {sport} once and hated it. Should I keep going?",
        "What's a couch to 5K plan?",
        "I'm embarrassed to exercise in public. Any tips?",
        "Do I need special shoes for {sport}?",
        "How do I breathe properly while {sport}?",
        "Is {sport} safe for someone who's never exercised?",
        "I'm a total newbie. What mistakes should I avoid?",
        "How long should my first training session be?",
        "I can only do 5 minutes before I'm gassed. Is that okay?",
        "Should I stretch before or after {sport}?",
        "I'm not athletic at all. Can I still learn to run?",
        "What heart rate should a beginner aim for?",
        "I'm starting from zero. How do I build a habit?",
        "Is it normal to be this slow as a beginner?",
        "I feel silly because everyone is faster than me.",
        "Should I join a beginners group or train alone?",
        "My first run was terrible. I wanted to quit after 2 minutes. Help.",
        "How do I avoid injury as a beginner?",
        "I want to start {sport} but I don't know any routes.",
        "Is there an age limit for starting {sport}?",
        "What should I eat before my first training session?",
        "I have no idea what I'm doing. Just tell me the basics.",
        "I'm a {experience} exerciser. Can I jump straight into a plan?",
        "Walking is all I can manage right now. Is that even training?",
        "I tried running and my {body} hurt. Should I stop?",
        "How quickly should I increase my training as a beginner?",
        "Everyone says start slow but I want to push myself!",
    ],
    "recovery": [
        "How long should I rest between hard workouts?",
        "What should I do on rest days?",
        "Is active recovery better than complete rest?",
        "I feel guilty taking rest days. Am I losing fitness?",
        "How do I know when I'm recovered enough for another hard session?",
        "What counts as active recovery?",
        "Should I do yoga on rest days?",
        "I took {days} rest days and feel slower. Did I rest too long?",
        "How important is sleep for recovery?",
        "Does stretching help with recovery?",
        "What about ice baths? Do they actually work?",
        "I can't sleep after evening training. How does that affect recovery?",
        "Should I eat differently on rest days?",
        "My legs still feel sore from {days} days ago. Am I recovered?",
        "How do I recover faster between sessions?",
        "Is foam rolling worth it?",
        "I feel restless on rest days. What can I do?",
        "Does massage help with recovery?",
        "My muscles are still tight from yesterday. Should I train?",
        "How many rest days per week do I need?",
        "Is walking considered recovery?",
        "I had a really hard week. How many rest days should I take?",
        "Does hydration affect recovery speed?",
        "My heart rate is elevated the morning after a hard session. Normal?",
        "I'm {age} — do I need more recovery than younger athletes?",
        "Rest days feel like wasted days. Change my mind.",
        "Should I take a full rest day or do something light?",
        "How do I know the difference between soreness and injury?",
        "I keep skipping rest days and getting injured. Help.",
        "Is it okay to do gentle {sport} on a rest day?",
        "How long does it take to fully recover from a race?",
        "I recovered fast when I was younger. Why is it slower now at {age}?",
        "Should I do compression socks or sleeves for recovery?",
        "My legs feel great the day after but terrible two days later. Why?",
        "What's the minimum recovery time between hard sessions?",
    ],
    "overtraining": [
        "I've been training hard for {weeks} weeks and my times are getting worse.",
        "I used to love training but now I dread it. What's wrong?",
        "My resting heart rate has been elevated for a week.",
        "I'm getting slower even though I'm training more. Why?",
        "I keep getting small injuries. Is that normal?",
        "I can't finish workouts that used to be easy.",
        "I feel moody and irritable since I increased my training.",
        "I'm not sleeping well even though I'm exhausted from training.",
        "I've lost my appetite but I'm training more than ever.",
        "My performance has plateaued for {weeks} weeks despite training hard.",
        "I get sick every time I increase my training load.",
        "I've been training {sessions} times a week and feel terrible.",
        "My legs are always heavy. Is that overtraining?",
        "I'm dreading every session. Should I take a break?",
        "I used to enjoy {sport} but now it feels like a chore.",
        "My heart rate is higher than usual during easy runs. Why?",
        "I've been doing too much, haven't I?",
        "I'm training a lot but getting weaker. What's happening?",
        "Every run feels harder than it should. Am I overtrained?",
        "I have no energy for anything outside of training.",
        "My motivation has completely disappeared.",
        "I keep getting colds and sore throats. Is that from training?",
        "I crash every afternoon after morning training.",
        "I've lost interest in {sport} after training so hard.",
        "My times were improving but now they're going backwards.",
        "I feel like I need a week off but I'm scared of losing fitness.",
        "My body aches all the time. Is that overtraining?",
        "I used to recover in a day. Now it takes {days} days.",
        "I can't shake this fatigue no matter how much I sleep.",
        "I increased my training by a lot and now everything hurts.",
        "Is there a way to tell if I'm overtrained or just in a bad patch?",
        "I feel burned out. How do I get my love for {sport} back?",
        "I've been pushing through tiredness for weeks. Bad idea?",
        "My easy pace is getting slower each week. Warning sign?",
        "I feel emotional and teary after training. Is that normal?",
    ],
    "motivation": [
        "I've lost motivation to train. What should I do?",
        "Training feels like a chore lately.",
        "I'm scared I'll fail my race. Should I even bother?",
        "I missed a week of training. Have I ruined everything?",
        "Everyone else seems faster than me. Should I quit?",
        "How do I stay motivated when progress is slow?",
        "I keep making excuses to skip training.",
        "I don't see the point anymore. Nothing is changing.",
        "I set a big goal but now it feels impossible.",
        "I've been training for {duration} and I'm not where I want to be.",
        "My training partner quit. Now I have no motivation.",
        "I'm afraid of failure. It's paralyzing me.",
        "I compare myself to everyone on social media and feel terrible.",
        "I was motivated for {weeks} weeks and then it just died.",
        "How do I get through a training slump?",
        "I feel like I'll never be good enough at {sport}.",
        "Rainy days kill my motivation completely.",
        "I missed {days} days of training and feel so guilty.",
        "I don't enjoy {sport} right now. Should I take a break?",
        "Everyone around me is improving except me.",
        "I signed up for a race and now I regret it.",
        "I'm not talented. Is there even a point in training?",
        "I keep starting and stopping. How do I stay consistent?",
        "My family doesn't understand why I train. It's discouraging.",
        "I had a bad race and lost all motivation.",
        "Training alone is depressing. I need accountability.",
        "I'm scared of getting injured again. It's holding me back.",
        "I feel like a fraud among real athletes.",
        "Some days I just don't want to get out of bed to train.",
        "I've been consistent for {duration} but the results aren't there.",
        "I'm {age} and wondering if it's too late to get serious.",
        "How do I find joy in training again?",
        "I feel overwhelmed by my training plan.",
        "I keep setting goals but never achieving them.",
        "I'm jealous of people who seem to love every workout.",
    ],
    "zones": [
        "What's Zone 2 and why does everyone talk about it?",
        "How do I know what zone I'm in without a heart rate monitor?",
        "Why do I have to stay in specific zones? Can't I just run?",
        "My zones feel wrong. Zone 2 feels too easy.",
        "What's the difference between Zone 3 and Zone 4?",
        "How many zones are there?",
        "Why is Zone 2 so slow? It barely feels like exercise.",
        "Should I spend most of my time in Zone 2?",
        "My heart rate goes really high really fast. Is something wrong?",
        "What zone should I be in for a long run?",
        "I can't keep my heart rate in Zone 2. It keeps going up.",
        "What zone should interval training be in?",
        "Is Zone 5 dangerous?",
        "How do I calculate my zones?",
        "My friend's zones are different from mine. Why?",
        "I always train in Zone 3. Is that bad?",
        "What's the 80/20 rule for zone training?",
        "Do zones change as I get fitter?",
        "My heart rate monitor says I'm in Zone 4 but I feel fine.",
        "Why does my heart rate jump around so much?",
        "What happens if I train in the wrong zone?",
        "I don't have a heart rate monitor. Can I still train with zones?",
        "What zone should recovery runs be in?",
        "Is it bad to spend time in Zone 3? Some people say it's a grey zone.",
        "How long should I train in Zone 5?",
        "My heart rate doesn't match how I feel. Which should I trust?",
        "Why do different apps show me different zones?",
        "I've heard Zone 2 is the fat-burning zone. True?",
        "What zone should my warmup be in?",
        "My heart rate is always high when I {sport}. Is that normal?",
        "How do I get better at staying in Zone 2?",
        "What does it mean to train polarized?",
        "I feel like zone training takes the fun out of {sport}.",
        "My max heart rate doesn't match the formula. Is that okay?",
        "Should I ignore zones and just go by feel?",
        "My heart rate is always high when I do {sport} in {weather} weather.",
        "I've been doing {sport} in Zone 2 for {weeks} weeks. When can I go harder?",
        "My Zone 2 heart rate during {sport} is different from {sport}. Normal?",
        "I'm {age} and my zones feel different from the formula.",
        "I trained in Zone 2 for {duration} and my fitness improved a lot.",
        "Zone 4 {sport} makes me feel sick. Is that normal?",
        "I did {sport} intervals and my heart rate stayed in Zone 5 for {days} minutes.",
        "My resting heart rate is lower now. Should my zones change?",
        "Heart rate zones for {sport} vs other sports — are they the same?",
        "I prefer training by perceived effort. Is that okay for {sport}?",
    ],
    "general": [
        "How do I get faster?",
        "What's more important — frequency or intensity?",
        "Should I follow a training plan or just wing it?",
        "How do I balance training with a busy work schedule?",
        "What mistakes do most beginners make?",
        "How many hours per week should I train?",
        "Is consistency more important than intensity?",
        "How do I know if I'm improving?",
        "Should I cross-train or stick to one sport?",
        "How long does it take to build a good fitness base?",
        "Is morning or evening training better?",
        "What's the best way to track my progress?",
        "How often should I do speed work?",
        "Should I train by time or distance?",
        "How do I set realistic training goals?",
        "Is it okay to train every day?",
        "What's the difference between training and exercising?",
        "How do I structure a training week?",
        "Should I focus on endurance or speed first?",
        "How important is warming up?",
        "Does strength training help with {sport}?",
        "How do I peak for an event?",
        "What's a taper and when should I do it?",
        "How do I avoid plateaus?",
        "Is it better to train more or train smarter?",
        "I can only train {days} days a week. Is that enough?",
        "How do I build endurance?",
        "Should I train the same way year-round?",
        "How do I know if my plan is working?",
        "What's the best training split for a week?",
        "How important is consistency vs intensity?",
        "I have {hours} hours per week. What's the best use of that time?",
        "Should I increase distance or speed first?",
        "What does progressive overload mean in {sport}?",
        "How do I plan my training around holidays?",
        "I've been doing {sport} for {duration}. What should my next goal be?",
        "Is {sport} {days} times a week enough to improve?",
        "I only do {sport} {time}. Should I switch?",
        "I've been training for {duration} and I'm still slow. What's wrong?",
        "Best way to structure {sport} training across {days} days?",
        "Does doing {sport} and strength training conflict?",
        "I'm {age} and want to get serious about {sport}.",
        "How do I balance {sport} with family life?",
        "I train {sport} {time}. Is that the best time?",
        "What's the minimum {sport} training to maintain fitness?",
    ],
    "injury_pain": [
        "My {body} hurts when I run. Should I stop?",
        "I have a sharp pain in my {body}. Is it serious?",
        "I've had {body} pain for {days} days. What should I do?",
        "Can I train through shin splints?",
        "My {body} is sore but it's not sharp pain. Is that okay?",
        "I pulled a muscle in my {body}. How long until I can train again?",
        "Should I use ice or heat for my sore {body}?",
        "I keep getting the same injury in my {body}. Why?",
        "Is it normal to be sore every day?",
        "My {body} clicks when I move. Should I worry?",
        "I'm scared to train because I keep getting injured.",
        "What's the difference between good pain and bad pain?",
        "I have runner's knee. Can I still cycle?",
        "My {body} swelled up after yesterday's run. What now?",
        "How do I prevent {body} injuries?",
        "I've been injured for {weeks} weeks. Am I losing all my fitness?",
        "Should I see a doctor or physio for my {body} pain?",
        "I get blisters every time I run. Help.",
        "My {body} hurts only when I {sport}. Not during other activities.",
        "Can I swim if my {body} hurts too much for {sport}?",
        "I'm coming back from a {body} injury. How do I start safely?",
        "I took painkillers and trained. Was that stupid?",
        "My {body} pain comes and goes. Should I still train?",
        "Is DOMS normal after hard training?",
        "How do I tell the difference between DOMS and an actual injury?",
        "I got injured doing speed work. Should I avoid fast training?",
        "My {body} has been tight for {weeks} weeks. How do I fix it?",
        "I'm injury-prone. What am I doing wrong?",
        "Should I stretch a sore {body}?",
        "I feel a twinge in my {body} during hard efforts. Normal?",
        "My physio says I can train but it still hurts. What do I do?",
        "I broke my {body} {duration} ago. When can I start {sport}?",
        "I get side stitches every time I run. Why?",
        "Plantar fasciitis is ruining my training. Help.",
        "I have IT band issues. Can I still train?",
    ],
    "nutrition": [
        "What should I eat before a morning workout?",
        "Do I need to eat during a long {sport} session?",
        "Should I eat before or after training?",
        "How important is protein for recovery?",
        "I want to lose weight but also train well. How?",
        "What should I eat the night before a race?",
        "How much water should I drink during training?",
        "Do I need sports drinks or is water enough?",
        "I feel sick if I eat before {sport}. What do I do?",
        "What are good snacks for between training sessions?",
        "Should I take supplements?",
        "How many calories should I eat on training days?",
        "I bonked during my long run. What went wrong?",
        "What should I eat after a hard workout?",
        "Is caffeine good for training performance?",
        "Do I need more carbs when I'm training a lot?",
        "I'm vegetarian. Is that a problem for endurance sports?",
        "How do I fuel during a race?",
        "I eat clean but still feel low on energy during training.",
        "Should I count calories or just eat intuitively?",
        "I'm trying to lose weight. Should I eat less on rest days?",
        "What do elite athletes eat before races?",
        "I get stomach cramps during {sport}. Is it my diet?",
        "How do I avoid the wall during a marathon?",
        "Is intermittent fasting compatible with training?",
        "I drink alcohol on weekends. How much does that hurt my training?",
        "Should I take electrolytes during training?",
        "I have no appetite after hard training. Should I force myself to eat?",
        "What's the best recovery meal?",
        "I eat pasta the night before every race. Good idea?",
        "Do I need gels during a {distance}?",
        "How much protein do I actually need?",
        "I'm always hungry on training days. How do I manage that?",
        "What should I eat during a {duration} training block?",
        "Is it bad to train on an empty stomach?",
    ],
    "race_prep": [
        "My first race is in {weeks} weeks. What should I expect?",
        "How should I taper before a {distance}?",
        "What pace should I start my race at?",
        "I'm nervous about my race. Is that normal?",
        "What should I wear for race day?",
        "How do I handle race day nerves?",
        "Should I try anything new on race day?",
        "My race is in {weeks} weeks. Am I ready?",
        "What's the best strategy for a {distance}?",
        "I'm doing my first {distance}. Any tips?",
        "Should I negative split or even split?",
        "What should I do the day before the race?",
        "How do I practice my race pace?",
        "I'm scared of hitting the wall. How do I prevent it?",
        "What's a realistic finish time for my first {distance}?",
        "Should I run the course before race day?",
        "I got sick {days} days before my race. Can I still run?",
        "What time should I wake up on race morning?",
        "I need a pre-race routine. What do you suggest?",
        "My race is hilly. How do I prepare?",
        "What if I need to use the bathroom during the race?",
        "Should I carry my own water or use aid stations?",
        "I'm afraid of coming last in the race.",
        "What mistakes do first-timers make on race day?",
        "Should I do a shakeout run the day before the race?",
        "My race has a cutoff time. I'm worried I won't make it.",
        "How do I deal with the first-mile adrenaline rush?",
        "It's going to be {weather} on race day. How do I adjust?",
        "I haven't finished my training plan but the race is soon. What now?",
        "Should I set a time goal or just aim to finish?",
        "How many races should I do per year?",
        "I had a terrible training block. Should I still race?",
        "Post-race blues are real. How do I handle them?",
        "What should I do the week after a race?",
        "I want to do my first triathlon. Where do I start?",
    ],
    "weather": [
        "It's {weather} today. Should I still train outside?",
        "How do I train when it's {weather}?",
        "Should I adjust my pace in {weather} weather?",
        "I hate training in the rain. What are my options?",
        "Is it safe to run in {weather} conditions?",
        "How do I stay cool when training in hot weather?",
        "What should I wear for {weather} training?",
        "I get overheated easily during summer training.",
        "How does heat affect my performance?",
        "Training in cold weather hurts my lungs. Is that normal?",
        "Should I skip outdoor training and go to the gym when it's {weather}?",
        "How do I adjust my zones in the heat?",
        "Is it dangerous to run in below-zero temperatures?",
        "I sweat a lot. How do I stay hydrated in {weather} weather?",
        "Wind makes my {sport} so much harder. How do I deal with it?",
        "Should I train indoors or outdoors in {weather} weather?",
        "I trained in the heat and felt awful. What happened?",
        "How long does it take to acclimate to hot weather?",
        "Winter makes me want to hibernate. How do I stay active?",
        "Is running in rain bad for you?",
        "My race is in a different climate. How do I prepare?",
        "What's the safest temperature range for outdoor training?",
        "I moved to a hot country. How does that affect my training?",
        "Ice on the roads makes running dangerous. Alternatives?",
        "UV index is really high. Should I avoid midday training?",
        "Does altitude affect my training?",
        "I live at sea level but my race is at altitude. Tips?",
        "Should I check the weather before every training session?",
        "I trained in direct sunlight and got dizzy. What went wrong?",
        "How do I dress for training when the weather changes mid-run?",
    ],
    "equipment": [
        "What running shoes should a beginner buy?",
        "Do I need a heart rate monitor?",
        "What's the best GPS watch for {sport}?",
        "Should I get a road bike or a hybrid?",
        "How often should I replace my running shoes?",
        "Are expensive shoes worth it?",
        "Do I need a power meter for cycling?",
        "What's the minimum gear I need for {sport}?",
        "My shoes are worn out. How can I tell?",
        "Should I get a bike fitting?",
        "What's the best budget watch for training?",
        "Do compression clothes actually help?",
        "I got new shoes and now my {body} hurts. Why?",
        "What's better — a chest strap or wrist heart rate monitor?",
        "Should I buy a treadmill for indoor training?",
        "Do I need special socks for running?",
        "What sunglasses are good for {sport}?",
        "Is a smart trainer worth the money?",
        "What clothes should I wear for {sport} in summer?",
        "What clothes should I wear for {sport} in winter?",
        "My watch says I burned 800 calories. Is that accurate?",
        "Do I need clipless pedals for cycling?",
        "What headphones are safe for outdoor {sport}?",
        "Should I wear a hat or visor when running?",
        "What's the best {sport} app?",
        "Do I need a foam roller?",
        "Is a turbo trainer the same as a smart trainer?",
        "What wetsuit do I need for triathlon?",
        "My watch and my gym's treadmill show different distances. Which is right?",
        "Should I get insoles for my running shoes?",
    ],
}


def has_placeholder(template):
    """Check if a template has {variable} placeholders."""
    return "{" in template and "}" in template


def generate_prompts(target_per_category=70) -> dict:
    """Generate prompts by filling templates with random variations."""
    result = {}
    seen = set()  # Deduplicate globally

    for category, templates in TEMPLATES.items():
        prompts = []
        # Target count: templates with variables can produce multiple variants
        target = target_per_category
        max_attempts = target * 20

        # First pass: one variant per template
        for template in templates:
            prompt = fill(template)
            if prompt not in seen:
                seen.add(prompt)
                prompts.append(prompt)

        # Second pass: generate more variants from templates with placeholders
        attempt = 0
        while len(prompts) < target and attempt < max_attempts:
            template = random.choice(templates)
            if has_placeholder(template):
                prompt = fill(template)
                if prompt not in seen:
                    seen.add(prompt)
                    prompts.append(prompt)
            attempt += 1

        result[category] = prompts

    return result


def main():
    output_path = Path(__file__).parent.parent / "data" / "test_prompts_1000.json"

    prompts = generate_prompts()
    total = sum(len(v) for v in prompts.values())

    with open(output_path, "w") as f:
        json.dump(prompts, f, indent=2)

    print(f"Generated {total} test prompts across {len(prompts)} categories")
    for cat, cat_prompts in prompts.items():
        print(f"  {cat}: {len(cat_prompts)}")
    print(f"\nWritten: {output_path}")


if __name__ == "__main__":
    main()
